version: '2'
services:
  mern_nginx:
    extends:
      file: docker-compose.yml
      service: mern_nginx
  mern_db:
    extends:
      file: docker-compose.yml
      service: mern_db
    volumes:
      - /data/mongodb:/data/db
  mern_website:
    extends:
      file: docker-compose.yml
      service: mern_website
    links:
      - mern_db
    env_file:
      - production.env

